linters-settings:
  depguard:
    rules:
      main:
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - "github.com/stretchr/testify/assert"
          - "noerrorcheck/config"
